<?php

/*This page takes input from addUser.php and creates a new user with that information.*/

//to connect to the database we do this
include('config.php');

//start the session so we can set global variables
//session_start();

//check that Name, LoginID, and password are populated
if(empty( $_POST['Name']))
{
    $message = 'All fields are required';
}

if(empty($_POST['LoginID']))
{
    $message = 'All fields are required';
}

if(empty($_POST['Password']))
{
    $message = 'All fields are required';
}

//Check LoginId length
elseif (strlen($_POST['LoginID']) > 32 || strlen($_POST['LoginID']) < 4)
{
    $message = 'LoginID length must be greater than 4 characters';
}

//check password length
elseif (strlen($_POST['Password']) > 32 || strlen($_POST['Password']) < 7)
{
    $message = 'Password length must be greater than 7 characters';
}

//Store Name, LoginID, and Passwords as variables
$Name = filter_var($_POST['Name'], FILTER_SANITIZE_STRING);
$LoginID = filter_var($_POST['LoginID'], FILTER_SANITIZE_STRING);
$Password = filter_var($_POST['Password'], FILTER_SANITIZE_STRING);

//hash the password
$PasswordHash = password_hash($Password, PASSWORD_DEFAULT);


//check if username is already taken



//REST url
$url=URL_START.'/public/api/users/LoginID/'.$LoginID;

$handle=fopen($url,"r");
if($handle){
   $jsonResponse=fgets($handle);
   fclose($handle);
   //login is not taken
   if(empty(json_decode($jsonResponse))){
      $link = connectDB();
      $sql = "INSERT INTO User VALUES (null, '".$LoginID."', '".$PasswordHash."', '".$Name."', 'Pending', null, null)";

      $result=mysqli_query($link,$sql);

      if(!$result)
      {
        $message = 'Query Failed';
      }

      if(mysqli_affected_rows($link) == 1) //if the insertion was successfull
      {
        $message = 'Thank you, your account is waiting for approval.';
        
        //log account creation
        //Add User to log
         $file = 'Log/createUser.log';
         
         //REST url
         //Here we pull the newest User, which is the one that was just created.
         $url = URL_START . '/public/api/users/newest';
         
         
         
         //open the file generated by the REST API
         $handle=fopen($url,"r");
         if($handle){
            $userInfo=fgets($handle);
            date_default_timezone_set("America/Denver");
            $currDate=date("Y-m-d h:i:sa");
            $ip = $_SERVER['REMOTE_ADDR']?:($_SERVER['HTTP_X_FORWARDED_FOR']?:$_SERVER['HTTP_CLIENT_IP']);
            $line='New User '.$userInfo.' Created on '.$currDate.' from '.$ip.PHP_EOL;
            file_put_contents($file,$line,FILE_APPEND | LOCK_EX);
            fclose($handle);
         }
         else{
            echo "error reading file (".$url.")";
         }
      }
   }
   //login is taken
   else
   {
      $message='Login ID is already taken';
   }
}
else{
   echo "Error reading file (".$url.")";
}




/*
try{
    //Connect to MYSQL Database mysqli(Server,User, Password,Database)
    $link = connectDB();

    $sql = "SELECT LoginID FROM User WHERE LoginID =  '".$LoginID."';";

    $result=mysqli_query($link,$sql);

    if(mysqli_num_rows($result) > 0) //if login id is already taken
    {
      $message = 'login id already taken';
    }

    else //insert if its a new login id
    {
      $sql = "INSERT INTO User VALUES (null, '".$LoginID."', '".$PasswordHash."', '".$Name."', 'Pending', null, null)";

      $result=mysqli_query($link,$sql);

      if(!$result)
      {
        $message = 'Query Failed';
      }

      if(mysqli_affected_rows($link) == 1) //if the insertion was successfull
      {
        $message = 'Thank you, your account is waiting for approval.';
      }
    }
}
catch(exception $e)
{
  $message = 'Unable to process request';
}*/

?>


<html>
    <head>
    <title>AddUserSubmit</title>
    </head>

    <body>
    <p></p><?php echo $message; ?>
    <form action="index.php" method="post">
      <input type="submit" value="Return"/>
    </form>
    </body>
</html>
