<?php

include("../config.php");
include("../header.php");

//check that all of the fields are populated correctly

//check that inputs are of valid lengths?

//set variables
//use filter_var to remove special characters from input
$NotificationID=$_POST['NotificationID'];

$NotificationTitle = filter_var($_POST['NotificationTitle'], FILTER_SANITIZE_STRING);
$NotificationDescription = filter_var($_POST['NotificationDescription'], FILTER_SANITIZE_STRING);
$PostDate = $_POST['PostDate'];

$PostTimeHour = filter_var($_POST['PostTimeHour'], FILTER_SANITIZE_STRING);
$PostTimeMinute = filter_var($_POST['PostTimeMinute'], FILTER_SANITIZE_STRING);
$PostTime = $PostTimeHour.":".$PostTimeMinute;

$PostTimeAMPM = $_POST['PostTimeAMPM'];


//REST url
//Here we pull the Event by ID to fetch its information before editing for the log file
$url = URL_START . "/public/api/notifications/id/".$NotificationID;

//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $notificationInfoOld=fgets($handle);
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}




/*********************************************
POST TO DATABASE VIA REST
*********************************************/

//Determine REST url
// REST url
$url = URL_START . '/public/api/notifications/edit/id/'.$NotificationID;

// Store session token in variable.
$token = $_SESSION['token'];

// Need to initiate curl
$ch = curl_init($url . '?authorization=' . $token);

// Create array for json data.
//Bind user input to request object
$jsonData = array(
    'NotificationTitle' => $NotificationTitle,
    'NotificationDescription' => $NotificationDescription,
    'PostDate' => $PostDate,
    'PostTime' => $PostTime,
    'PostTimeAMPM' => $PostTimeAMPM
);


// Need to encode this array into json.
$jsonDataEncoded = json_encode($jsonData);

// curl hands the post request
curl_setopt($ch, CURLOPT_POST, 1);

// json string is now attached to the post fields.
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);

// Set the content type to application/json.
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));

// Need to execute the request.
$result = curl_exec($ch);


//Add Event to log
$file = '../Log/editNotification.log';

//REST url
//Here we pull the Event by ID to fetch its information
$url = URL_START . "/public/api/notifications/id/".$NotificationID;



//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $notificationInfoNew=fgets($handle);
   date_default_timezone_set("America/Denver");
   $currDate=date("Y-m-d h:i:sa");
   $ip = $_SERVER['REMOTE_ADDR']?:($_SERVER['HTTP_X_FORWARDED_FOR']?:$_SERVER['HTTP_CLIENT_IP']);
   $line='User (ID:'.$_SESSION['userID'].', User Name:'.$_SESSION['LoginID'].') on '.$currDate.' from '.$ip.' Edited From: '.$notificationInfoOld.' To: '.$notificationInfoNew.PHP_EOL;
   file_put_contents($file,$line,FILE_APPEND | LOCK_EX);
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}



//Below is the old method of editing
/*
try
{
   //Connect to CRUD Database  mysqli(Server,User,Password,Database)
   $link = connectDB();

   $sql = "UPDATE Notification SET Title = '".$NotificationTitle."', Description = '".$NotificationDescription."', PostDate = '".$PostDate."', PostTime = '".$PostTime."', PostTimeAMPM = '".$PostTimeAMPM."' WHERE ID = '".$NotificationID."'";
   if (mysqli_query($link, $sql))
   {
      $message = 'Notification edited.';
   }
   else
   {
      echo  "<br>Error: " . $sql . "<br>" . mysqli_error($link);
   }
}
catch(Exception $e)
{
   $message = 'Unable to process request';
}*/

?>

<html>

   <p>
      <?php echo $message;?>
      <form action="editNotification" method="post">
         <input type="hidden" name="NotificationID" value="<?php echo $NotificationID;?>"/>
         <input type="submit" value="Return"/>
      </form>
   </p>

</html>
