<?php
include("../config.php");
include("../header.php");


$EventID = $_POST['eventID'];

//get selected media info
$Media1 = null;//$_FILES['media1']['name'];
$Media2 = $_FILES['media2']['name'];
$Media3 = $_FILES['media3']['name'];

$url = URL_START . 'public/api/events/id/'.$EventID;

//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $eventInfoOld=fgets($handle);
   
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}

/*********************************************
POST TO DATABASE VIA REST
*********************************************/
$url = URL_START . 'public/api/events/remove/id/'.$EventID;

// Store session token in variable.
$token = $_SESSION['token'];

// Need to initiate curl
$ch = curl_init($url . '?authorization=' . $token);

// Create array for json data.
//Bind user input to request object
$jsonData = array(
    'EventMedia1' => $Media1,
    'EventMedia2' => $Media2,
    'EventMedia3' => $Media3
);

// Need to encode this array into json.
$jsonDataEncoded = json_encode($jsonData);

// curl hands the post request
curl_setopt($ch, CURLOPT_POST, 1);

// json string is now attached to the post fields.
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);

// Set the content type to application/json.
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));

// Need to execute the request.
$result = curl_exec($ch);


//Add Event to log
$file = '../Log/editEventDeleteMedia.log';

//REST url
//Here we pull the newest Event, which is the one that was just created.
$url= URL_START ."/public/api/events/id/".$EventID;


//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $eventInfoNew=fgets($handle);
   date_default_timezone_set("America/Denver");
   $currDate=date("Y-m-d h:i:sa");
   $ip = $_SERVER['REMOTE_ADDR']?:($_SERVER['HTTP_X_FORWARDED_FOR']?:$_SERVER['HTTP_CLIENT_IP']);
   $line='User (ID:'.$_SESSION['userID'].', User Name:'.$_SESSION['LoginID'].') on '.$currDate.' from '.$ip.' Edited From: '.$eventInfoOld.' To: '.$eventInfoNew.PHP_EOL;
   file_put_contents($file,$line,FILE_APPEND | LOCK_EX);
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}


?>


<html>

   <p>
      <?php echo $message;?>
      <form action="editEvent" method="post">
         <input type="hidden" name="EventID" value="<?php echo $EventID;?>"/>
         <input type="submit" value="Return"/>
      </form>
   </p>

</html>














