<?php

include("../config.php");
include("../header.php");

//set variables
//use filter_var to remove special characters from input
$EventID=$_POST['EventID'];

$EventTitle = filter_var($_POST['EventTitle'], FILTER_SANITIZE_STRING);
$EventCategory = filter_var($_POST['EventCategory'], FILTER_SANITIZE_STRING);
$EventDate = $_POST['EventDate'];

$EventStartTimeHour = filter_var($_POST['EventStartTimeHour'], FILTER_SANITIZE_STRING);
$EventStartTimeMinute = filter_var($_POST['EventStartTimeMinute'], FILTER_SANITIZE_STRING);
$EventStartTime = $EventStartTimeHour.":".$EventStartTimeMinute;

$EventStartTimeAMPM = $_POST['EventStartTimeAMPM'];
$EventLocation = filter_var($_POST['EventLocation'], FILTER_SANITIZE_STRING);
$EventDescription = filter_var($_POST['EventDescription'], FILTER_SANITIZE_STRING);

//target directory
$target_media1 = "../media/".basename($_FILES['media1']['name']);
$target_media2 = "../media2/".basename($_FILES['media2']['name']);
$target_media3 = "../media3/".basename($_FILES['media3']['name']);
  
//move media file to the media folder
move_uploaded_file($_FILES['media1']['tmp_name'], $target_media1);
move_uploaded_file($_FILES['media2']['tmp_name'], $target_media2);
move_uploaded_file($_FILES['media3']['tmp_name'], $target_media3);
    
//get selected media info
$Media1 = $_FILES['media1']['name'];
$Media2 = $_FILES['media2']['name'];
$Media3 = $_FILES['media3']['name'];

//REST url
//Here we pull the Event by ID to fetch its information before editing for the log file
$url = URL_START . "/public/api/events/id/".$EventID;

//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $eventInfoOld=fgets($handle);
   
   //If no file was specified, then Media is not updated, and is instead made to be the same file it was before.
   foreach(json_decode($eventInfoOld,true) as $row){
      if(empty($Media1))$Media1=$row['Media1'];
      if(empty($Media2))$Media2=$row['Media2'];
      if(empty($Media3))$Media3=$row['Media3'];
   }
   
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}




/*********************************************
POST TO DATABASE VIA REST
*********************************************/

//Determine REST url
// REST url
$url = URL_START . '/public/api/events/edit/id/'.$EventID;

// Store session token in variable.
$token = $_SESSION['token'];

// Need to initiate curl
$ch = curl_init($url . '?authorization=' . $token);

// Create array for json data.
//Bind user input to request object
$jsonData = array(
    'EventTitle' => $EventTitle,
    'EventCategory' => $EventCategory,
    'EventDate' => $EventDate,
    'EventStartTime' => $EventStartTime,
    'EventStartTimeAMPM' => $EventStartTimeAMPM,
    'EventLocation' => $EventLocation,
    'EventDescription' => $EventDescription,
    'EventMedia1' => $Media1,
    'EventMedia2' => $Media2,
    'EventMedia3' => $Media3
);


// Need to encode this array into json.
$jsonDataEncoded = json_encode($jsonData);

// curl hands the post request
curl_setopt($ch, CURLOPT_POST, 1);

// json string is now attached to the post fields.
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);

// Set the content type to application/json.
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));

// Need to execute the request.
$result = curl_exec($ch);


//Add Event to log
$file = '../Log/editEvent.log';

//REST url
//Here we pull the Event by ID to fetch its information
$url = URL_START . "/public/api/events/id/".$EventID;



//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $eventInfoNew=fgets($handle);
   date_default_timezone_set("America/Denver");
   $currDate=date("Y-m-d h:i:sa");
   $ip = $_SERVER['REMOTE_ADDR']?:($_SERVER['HTTP_X_FORWARDED_FOR']?:$_SERVER['HTTP_CLIENT_IP']);
   $line='User (ID:'.$_SESSION['userID'].', User Name:'.$_SESSION['LoginID'].') on '.$currDate.' from '.$ip.' Edited From: '.$eventInfoOld.' To: '.$eventInfoNew.PHP_EOL;
   file_put_contents($file,$line,FILE_APPEND | LOCK_EX);
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}



//Below is the old way of editing
/*
try
{
  //Connect to CRUD Database  mysqli(Server,User,Password,Database)
  $link = connectDB();
    
  //$sql = "UPDATE CalendarEvent SET Title = '".$EventTitle."', Category = '".$EventCategory."', EventDate = '".$EventDate."', EventStartTime = '".$EventStartTime."', EventStartTimeAMPM = '".$EventStartTimeAMPM."', Location = '".$EventLocation."', Description = '".$EventDescription."', Media1 = '".$Media1."', Media2 = '".$Media2."', Media3 = '".$Media3."' WHERE ID = '".$EventID."'";
  
  if(!empty($Media1))//media1 is not empty run query to upload media into media1 slot
  {
    $sql = "UPDATE CalendarEvent SET Title = '".$EventTitle."', Category = '".$EventCategory."', EventDate = '".$EventDate."', EventStartTime = '".$EventStartTime."', EventStartTimeAMPM = '".$EventStartTimeAMPM."', Location = '".$EventLocation."', Description = '".$EventDescription."', Media1 = '".$Media1."' WHERE ID = '".$EventID."'";
  }
  else if(!empty($Media2))//media2 is not empty run query to upload media into media2 slot
  {
    $sql = "UPDATE CalendarEvent SET Title = '".$EventTitle."', Category = '".$EventCategory."', EventDate = '".$EventDate."', EventStartTime = '".$EventStartTime."', EventStartTimeAMPM = '".$EventStartTimeAMPM."', Location = '".$EventLocation."', Description = '".$EventDescription."', Media2 = '".$Media2."' WHERE ID = '".$EventID."'";
  }
  else if(!empty($Media3))//media3 is not empty run query to upload media into media3 slot
  {
    $sql = "UPDATE CalendarEvent SET Title = '".$EventTitle."', Category = '".$EventCategory."', EventDate = '".$EventDate."', EventStartTime = '".$EventStartTime."', EventStartTimeAMPM = '".$EventStartTimeAMPM."', Location = '".$EventLocation."', Description = '".$EventDescription."', Media3 = '".$Media3."' WHERE ID = '".$EventID."'";
  }
  else//updates all feilds except media1, media2, and media3
  {
    $sql = "UPDATE CalendarEvent SET Title = '".$EventTitle."', Category = '".$EventCategory."', EventDate = '".$EventDate."', EventStartTime = '".$EventStartTime."', EventStartTimeAMPM = '".$EventStartTimeAMPM."', Location = '".$EventLocation."', Description = '".$EventDescription."' WHERE ID = '".$EventID."'";
  }
  
  if (mysqli_query($link, $sql))
  {
    $message = 'Event edited.';
  }
  else
  {
    echo  "<br>Error: " . $sql . "<br>" . mysqli_error($link);
  }
}
catch(Exception $e)
{
  $message = 'Unable to process request';
}
*/

?>

<html>

   <p>
      <?php echo $message;?>
      <form action="editEvent" method="post">
         <input type="hidden" name="EventID" value="<?php echo $EventID;?>"/>
         <input type="submit" value="Return"/>
      </form>
   </p>

</html>
