<?php
include ('../header.php');
include('../config.php');

/***********************************************************
 * Output all of the user accounts info onto the screen in *
 * descending order based on the account's id.             *
 ***********************************************************/
echo "<html><head><h1>Account List</h1></head>";


//REST url
$url = URL_START . "/public/api/users/order/ID/sort/desc";

//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $jsonResponse=fgets($handle);
   
   echo '<table align="center" style="width:100%">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>LoginID</th>
            <th>AccountStatus</th>
            <th>Edit Account</th>
          </tr>';
          
   foreach(json_decode($jsonResponse,true) as $row){
      echo '<tr><td align="center">' .
        $row['ID'] . '</td><td align="center">' .
        $row['Name'] . '</td><td align="center">' .
        $row['LoginID'] . '</td><td align="center">' .
        $row['AccountStatus'] . '</td><td align="center">';

      echo '<form action="accountManagementAccountInfo" method="post">' .
           '<input type="hidden" name="LoginID" value="'.$row['LoginID'].'"/>' .
           '<input type="submit" value="Manage Account Info"/>' .
           '</form>' .
           '</td>';

      echo '</tr>';
   }
   echo "</tr>";
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}


//Below is the old way of listing account info
/*
try
{
  $link = connectDB();
  $sql = "SELECT * FROM User ORDER BY ID DESC;";

  if($result = mysqli_query($link, $sql))
  {
    echo '<table align="center" style="width:100%">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>LoginID</th>
            <th>AccountStatus</th>
            <th>Edit Account</th>
          </tr>';

    while($row = mysqli_fetch_array($result))
    {
      echo '<tr><td align="center">' .
        $row['ID'] . '</td><td align="center">' .
        $row['Name'] . '</td><td align="center">' .
        $row['LoginID'] . '</td><td align="center">' .
        $row['AccountStatus'] . '</td><td align="center">';

      echo '<form action="accountManagementAccountInfo" method="post">' .
           '<input type="hidden" name="LoginID" value="'.$row['LoginID'].'"/>' .
           '<input type="submit" value="Manage Account Info"/>' .
           '</form>' .
           '</td>';

      echo '</tr>';
    }//end while
    echo "</tr>";
  }//end if
}//end try
catch(Exception $e)
{
  $message = 'Unable to process request';
}
*/
?>

  <body>
  <p><?php echo $message; ?></p>
  </body>

</html>
