<?php
include ('../header.php');
include('../config.php');

//Get request to fetch information on event
// REST url
$id=$_SESSION['userID'];
//$login = $_SESSION['LoginID'];//$_POST['LoginID'];
$url = URL_START."/public/api/users/id/".$id;//$url = URL_START."/public/api/users/LoginID/".$login;

   //open the file generated by the REST API
   $handle=fopen($url,"r");
   if($handle){
      while(($line=fgets($handle))!==false){  
         $row=json_decode($line,true);
         $row=$row[0];
         
         //set all variables
         $ID=$_row['ID'];
         $name = $row['Name'];
         $loginid = $row['LoginID'];
         $password = $row['Password'];
         $accountStatus = $row['AccountStatus'];
      }
      fclose($handle);
   }
   //If file cannot be read, an error is shown
   else{
      echo "error reading file (".$url.")";
   }

//Below is the old way of editing
/**************************************************************************
 * Output the user's info onto the screen. The name will                  *
 * be the only variable that the user will be able to edit.               *
 * The id will be hidden, name and the account status will be read only. *
 **************************************************************************/
/*try
{
  $link = connectDB();
  $sql = "SELECT * FROM User WHERE LoginID ='".$_SESSION['LoginID']."';";

  if($result = mysqli_query($link, $sql))
  {
    while($row=mysqli_fetch_assoc($result))
    {
      $id = $row['ID'];
      $name = $row['Name'];
      $loginid = $row['LoginID'];
      $accountStatus = $row['AccountStatus'];
    }//end while
  }//end if
}
catch(exception $e)
{
  $message = 'Unable to proccess request';
}*/
?>

<html>
  <form action="accountManagementMyAccountInfoSubmit" method="post">
  <fieldset>

    <h1><strong>Manage My Account Info</strong></h1>

    <input type="hidden" name="ID" value="<?php echo $ID?>" />

    <p>
      <label>Name</label>
      <input name="Name" value="<?php echo $name?>" maxlength="128"/>
      <i>(maximum length of 128 characters)</i>
    </p>

    <p>
      <label>LoginID</label>
      <input readonly="readonly" name="LoginID" value="<?php echo $loginid?>"/>
    </p>
    
    <p>
      <input type="hidden" name="Password" value="<?php echo $password ?>"/>
    </p>

    <p>
      <label>Account Status</label>
      <input readonly="readonly" name="AccountStatus" value="<?php echo $accountStatus?>" />
    </p>
    
    <h2><strong>Reset Password</strong></h2>
    
    <p>
      <label>New Password:</label>
      <input type="password" name="NewPassword" value="" minlength="7" />
      <i>(Password must be between 7 and 32 characters long)</i>
    </p>
    
    <p>
      <label>Confirm New Password:</label>
      <input type="password" name="ConfirmNewPassword" value="" minlength="7" />
      <i>(Password must be between 7 and 32 characters long)</i>
    </p>

    <p>
    <input type="submit" value="Edit Info" />
    </p>

  </fieldset>
  </form>

</html>
