<?php
include("../config.php");
include("../header.php");

/********************************************
 * Update the database with the edited info *
 * from the user.                           *
 ********************************************/
$id = $_POST['ID'];
$accountStatus = filter_var($_POST['AccountStatus'], FILTER_SANITIZE_STRING);

//fetch old account info

$url = URL_START . "/public/api/users/id/".$id;

//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $userInfoOld=fgets($handle);
   
   foreach(json_decode($userInfoOld,true) as $row){
      $name = $row['Name'];
      $loginid = $row['LoginID'];
      $PasswordHash = $row['Password'];
   }

   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}

//update user info

//Determine REST url
// REST url
$url = URL_START . "/public/api/users/edit/id/".$id;

// Store session token in variable.
$token = $_SESSION['token'];

// Need to initiate curl
$ch = curl_init($url . '?authorization=' . $token);

// Create array for json data.
//Bind user input to request object
$jsonData = array(
   'ID' => $id,
   'Name' => $name,
   'LoginID' => $loginid,
   'AccountStatus' => $accountStatus,
   'Password' => $PasswordHash
);

// Need to encode this array into json.
$jsonDataEncoded = json_encode($jsonData);

// curl hands the post request
curl_setopt($ch, CURLOPT_POST, 1);

// json string is now attached to the post fields.
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);

// Set the content type to application/json.
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));

// Need to execute the request.
$result = curl_exec($ch);

//Add to log
$file = '../Log/accountManagementAccountInfo.log';

//REST url
//Here we pull the newest Event, which is the one that was just created.
$url = URL_START . "/public/api/users/id/".$id;//URL_START . "/public/api/users/id/".$id;

//open the file generated by the REST API
$handle=fopen($url,"r");
if($handle){
   $userInfoNew=fgets($handle);
   date_default_timezone_set("America/Denver");
   $currDate=date("Y-m-d h:i:sa");
   $ip = $_SERVER['REMOTE_ADDR']?:($_SERVER['HTTP_X_FORWARDED_FOR']?:$_SERVER['HTTP_CLIENT_IP']);
   $line='User (ID:'.$_SESSION['userID'].', User Name:'.$_SESSION['LoginID'].') on '.$currDate.' from '.$ip.' Edited From: '.$userInfoOld.' To: '.$userInfoNew.PHP_EOL;
   file_put_contents($file,$line,FILE_APPEND | LOCK_EX);
   fclose($handle);
}
else{
   echo "error reading file (".$url.")";
}







//Below is the old way of editing account information
/*

try
{
  $link = connectDB();
  $sql = "UPDATE User SET AccountStatus = '".$accountStatus."' WHERE ID = '".$id."'";

  if($result=mysqli_query($link,$sql))
  {
    $message = 'Account updated.';
  }
  else
  {
    echo "<br>Error: " . $sql . "<br>" . mysqli_error($link);
  }
}
catch(exception $e)
{
  $message = 'Unable to process request.';
}*/

?>

<html>
  <p>
    <?php echo $message; ?>
    <form action="accountManagementAccountInfo" method="post">
      <input type="hidden" name="ID" value="<?php echo $id; ?>"/>
      <input type="submit" value="Return"/>
    </form>
  </p>
</html>
